# Streamlit secrets for VSBVibeCode
openai_api_key = "sk-REPLACE_ME"

# Optional (for later steps)
supabase_url = ""
supabase_anon_key = ""
github_pat = ""

# Default model (we will always use GPT-5 Mini unless user overrides later)
openai_model = "gpt-5-mini"